import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "~/components";
import { HomePage } from "~/layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Joy Games | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <HomePage />
    </div>
  );
};

export default Home;
