import type { NextPage } from "next";
import Head from "next/head";
import { Layout, Navbar } from "~/components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Joy Games | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
    </div>
  );
};

export default Home;
